"""initial schema

Revision ID: 16694b4ff75e
Revises: 
Create Date: 2026-06-30 22:18:49.159215
"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = '16694b4ff75e'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teams',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('short_name', sa.String(length=60), nullable=True),
    sa.Column('country_code', sa.String(length=8), nullable=True),
    sa.Column('crest_url', sa.String(length=400), nullable=True),
    sa.Column('external_ref', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='app'
    )
    op.create_table('tournaments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('sport', sa.String(length=40), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('format_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('scoring_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug'),
    schema='app'
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', postgresql.CITEXT(), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('auth_provider', sa.String(length=20), nullable=False),
    sa.Column('auth_subject', sa.String(length=255), nullable=True),
    sa.Column('timezone', sa.String(length=60), nullable=False),
    sa.Column('locale', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('auth_provider', 'auth_subject', name='uq_user_auth_subject'),
    sa.UniqueConstraint('email'),
    schema='app'
    )
    op.create_table('brackets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('tournament_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_score', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tournament_id'], ['app.tournaments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['app.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'tournament_id', 'name', name='uq_bracket'),
    schema='app'
    )
    op.create_table('conversations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('thread_id', sa.String(length=255), nullable=False),
    sa.Column('tournament_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('last_message_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['tournament_id'], ['app.tournaments.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['app.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('thread_id'),
    schema='app'
    )
    op.create_table('favorite_teams',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('team_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['app.teams.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['app.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'team_id', name='uq_fav'),
    schema='app'
    )
    op.create_table('fixtures',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tournament_id', sa.UUID(), nullable=False),
    sa.Column('external_ref', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('stage', sa.String(length=40), nullable=True),
    sa.Column('round_key', sa.String(length=40), nullable=True),
    sa.Column('group_label', sa.String(length=8), nullable=True),
    sa.Column('home_team_id', sa.UUID(), nullable=True),
    sa.Column('away_team_id', sa.UUID(), nullable=True),
    sa.Column('home_placeholder', sa.String(length=80), nullable=True),
    sa.Column('away_placeholder', sa.String(length=80), nullable=True),
    sa.Column('kickoff_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('venue', sa.String(length=160), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('home_score', sa.Integer(), nullable=True),
    sa.Column('away_score', sa.Integer(), nullable=True),
    sa.Column('home_score_et', sa.Integer(), nullable=True),
    sa.Column('away_score_et', sa.Integer(), nullable=True),
    sa.Column('home_pens', sa.Integer(), nullable=True),
    sa.Column('away_pens', sa.Integer(), nullable=True),
    sa.Column('winner_team_id', sa.UUID(), nullable=True),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['away_team_id'], ['app.teams.id'], ),
    sa.ForeignKeyConstraint(['home_team_id'], ['app.teams.id'], ),
    sa.ForeignKeyConstraint(['tournament_id'], ['app.tournaments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['winner_team_id'], ['app.teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='app'
    )
    op.create_table('leagues',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tournament_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('owner_user_id', sa.UUID(), nullable=False),
    sa.Column('invite_code', sa.String(length=16), nullable=False),
    sa.Column('visibility', sa.String(length=20), nullable=False),
    sa.Column('scoring_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('max_members', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['owner_user_id'], ['app.users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tournament_id'], ['app.tournaments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invite_code'),
    schema='app'
    )
    op.create_table('tournament_teams',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tournament_id', sa.UUID(), nullable=False),
    sa.Column('team_id', sa.UUID(), nullable=False),
    sa.Column('group_label', sa.String(length=8), nullable=True),
    sa.Column('seed', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['app.teams.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tournament_id'], ['app.tournaments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tournament_id', 'team_id', name='uq_tt'),
    schema='app'
    )
    op.create_table('bracket_picks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('bracket_id', sa.UUID(), nullable=False),
    sa.Column('fixture_id', sa.UUID(), nullable=True),
    sa.Column('round_key', sa.String(length=40), nullable=False),
    sa.Column('pick_type', sa.String(length=30), nullable=False),
    sa.Column('predicted_winner_team_id', sa.UUID(), nullable=True),
    sa.Column('predicted_home_score', sa.Integer(), nullable=True),
    sa.Column('predicted_away_score', sa.Integer(), nullable=True),
    sa.Column('predicted_team_id', sa.UUID(), nullable=True),
    sa.Column('points_awarded', sa.Integer(), nullable=True),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.Column('scored_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['bracket_id'], ['app.brackets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['fixture_id'], ['app.fixtures.id'], ),
    sa.ForeignKeyConstraint(['predicted_team_id'], ['app.teams.id'], ),
    sa.ForeignKeyConstraint(['predicted_winner_team_id'], ['app.teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='app'
    )
    op.create_table('briefings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('fixture_id', sa.UUID(), nullable=False),
    sa.Column('tournament_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('content_format', sa.String(length=20), nullable=False),
    sa.Column('model', sa.String(length=80), nullable=True),
    sa.Column('thread_id', sa.String(length=255), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['fixture_id'], ['app.fixtures.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tournament_id'], ['app.tournaments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['app.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='app'
    )
    op.create_table('league_memberships',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('league_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('bracket_id', sa.UUID(), nullable=True),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['bracket_id'], ['app.brackets.id'], ),
    sa.ForeignKeyConstraint(['league_id'], ['app.leagues.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['app.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('league_id', 'user_id', name='uq_membership'),
    schema='app'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('league_memberships', schema='app')
    op.drop_table('briefings', schema='app')
    op.drop_table('bracket_picks', schema='app')
    op.drop_table('tournament_teams', schema='app')
    op.drop_table('leagues', schema='app')
    op.drop_table('fixtures', schema='app')
    op.drop_table('favorite_teams', schema='app')
    op.drop_table('conversations', schema='app')
    op.drop_table('brackets', schema='app')
    op.drop_table('users', schema='app')
    op.drop_table('tournaments', schema='app')
    op.drop_table('teams', schema='app')
    # ### end Alembic commands ###
